dist: trusty
language: rust
services: docker
env:
  global:
  - CRATE_NAME=tmpo
jobs:
  include:
  - env: TARGET=aarch64-unknown-linux-gnu
  - env: TARGET=arm-unknown-linux-gnueabi
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=x86_64-pc-windows-gnu
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
before_install:
- set -e
- rustup self update
install:
- sh scripts/install.sh
- source ~/.cargo/env || true
script:
- bash scripts/test.sh
after_script: set +e
before_deploy:
- sh scripts/before_deploy.sh
deploy:
  provider: releases
  token:
    secure: VBTLVORsSBXhvNTjg0TvKxgn7eytOtr5pfX5Cdm700KHMJBqUJvrHiTzkPqeMhhxgfTgicJ6XYTvszjabA+TDNFVosVROgcxUKANOpszAHc1IlTWgmR2B/V8yo+rW6o0UnV3wbDZa4gdG/thkKy+sZ9Me8Zlt3m63Rg7moPo9GW/yoLc4kK2rn0JFLmT2CM64bNMOKzANep8DGHCdz11f4jRIktJcVPbAiRAODSG0qEP9URQkYf96CWsET9q+ZS7g2doQ23SH+yQMcoN3L4IxsjRmu4/xjc6m1mFsxh1jXfaFJLBJModyj2Bgyu8aw1lBsdY0Vg8qbZ/SVpsbNqR2pnZuNZjzyubrf34EAV08xBAReZc/MT0dcU2WZm6jO/qK1T5pMMGOblZGRTJignSPKjYqBq6EjdJinJCTYGKYQYPwMIbpC0l14yS6b+ZSmeyeVnskeQXL8KiTglNVLGuwMdtJbqKd0DHcSv7QsPEZqDIe5xbC+KqivUqXM09LiyVM7CpICtA5QzmdS8JHxJZI9DRlu0PrQJe9fbr6XrY+PEYpNI5ce8UYkUmp1HhxBk3vS8GntCozo3DvPbVkshWbx1jPyE/7rkukNe0ksFKhGcDpa6PNApywvpbW0PVR3bkLWW1/Gl+cGMQW8lrbpS61WeipREoi/DhA9EMuEbWB7o=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    repo: perryrh0dan/tmpo
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
