[package]
name = "tmpo"
version = "1.5.3"
authors = ["Thomas Pöhlmann <thomaspoehlmann96@googlemail.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
serde_yaml = "0.8.13"
dirs = "3.0.1"
log = "0.4.8"
log4rs = "0.13.0"
git2 = "0.13"
colored = "2.0.0"
dialoguer = "0.6.2"
reqwest = { version ="0.10.8"}
tempfile = "3.1.0"
flate2 = "1.0.17"
tar = "0.4.29"
handlebars = "3.4.0"

[dependencies.self_update]
version = "0.20"
features = ["archive-tar"]

[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10.30", features = ["vendored"] }

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1"
